--Part 1
USE movies

--Problem 1
SELECT
	m.TITLE,
	m.YEAR,
	m.LENGTH
FROM MOVIE AS m
WHERE m.LENGTH > 120 AND m.YEAR < 2000
	OR m.LENGTH IS NULL

--Problem 2
SELECT
	ms.NAME,
	ms.GENDER
FROM MOVIESTAR AS ms
WHERE ms.NAME LIKE 'J%'
	AND ms.BIRTHDATE > 1948
ORDER BY ms.NAME DESC

--Problem 3
SELECT 
	m.STUDIONAME,
	COUNT(DISTINCT s.STARNAME) AS NumberOfActors
FROM MOVIE AS m
JOIN STARSIN AS s
	ON m.TITLE = s.MOVIETITLE
GROUP BY m.STUDIONAME

--Problem 4
SELECT 
	ms.NAME,
	COUNT(m.TITLE) AS NumberOfMovies
FROM MOVIESTAR AS ms
LEFT JOIN STARSIN AS s
	ON ms.NAME = s.STARNAME
LEFT JOIN MOVIE AS m
	ON s.MOVIETITLE = m.TITLE
GROUP BY ms.NAME

--Problem 5
SELECT 
	m1.STUDIONAME,
	m1.TITLE,
	m1.YEAR
FROM MOVIE AS m1
WHERE m1.TITLE = (
	SELECT TOP(1)
		m2.TITLE
	FROM MOVIE AS m2
	WHERE m2.STUDIONAME = m1.STUDIONAME
	ORDER BY m2.YEAR DESC
)
AND m1.YEAR = (
	SELECT TOP(1)
		m2.YEAR
	FROM MOVIE AS m2
	WHERE m2.STUDIONAME = m1.STUDIONAME
	ORDER BY m2.YEAR DESC
)
ORDER BY m1.YEAR DESC

--Problem 6
SELECT TOP(1)
	ms.NAME
FROM MOVIESTAR AS ms
WHERE ms.GENDER = 'm'
ORDER BY ms.BIRTHDATE DESC

--Problem 7
SELECT
	m.STUDIONAME,
	s.STARNAME,
	COUNT(m.TITLE) AS MoviesCount
FROM STARSIN AS s
JOIN MOVIE AS m 
	ON s.MOVIETITLE = m.TITLE
GROUP BY s.STARNAME, m.STUDIONAME
HAVING COUNT(m.TITLE) >= ALL (
	SELECT
		COUNT(m2.TITLE)
	FROM STARSIN AS s2
	JOIN MOVIE AS m2
		ON s2.MOVIETITLE = m2.TITLE
	WHERE m2.STUDIONAME = m.STUDIONAME
	GROUP BY s2.STARNAME, m2.STUDIONAME
)

--OR

SELECT
	m.STUDIONAME,
	s.STARNAME,
	COUNT(m.TITLE) AS MoviesCount
FROM STARSIN AS s
JOIN MOVIE AS m 
	ON s.MOVIETITLE = m.TITLE
GROUP BY s.STARNAME, m.STUDIONAME
HAVING COUNT(m.TITLE) = (
	SELECT TOP(1)
		COUNT(m2.TITLE) AS mCount
	FROM STARSIN AS s2
	JOIN MOVIE AS m2
		ON s2.MOVIETITLE = m2.TITLE
	WHERE m2.STUDIONAME = m.STUDIONAME
	GROUP BY s2.STARNAME, m2.STUDIONAME
	ORDER BY mCount DESC
)

--Problem 8
SELECT
	s.MOVIETITLE,
	s.MOVIEYEAR,
	COUNT(s.STARNAME) AS StarCount
FROM STARSIN AS s
GROUP BY s.MOVIETITLE, s.MOVIEYEAR
HAVING COUNT(s.STARNAME) > 2

--Part 2
USE ships

--Part 3
USE pc