--Part 1
USE movies

--Problem 1
SELECT
	m.TITLE,
	me.NAME
FROM MOVIEEXEC AS me
JOIN MOVIE AS m
	ON me.CERT# = m.PRODUCERC#
WHERE me.NAME = (
	SELECT
		me.NAME
	FROM MOVIEEXEC AS me
	JOIN MOVIE	AS m
		ON me.CERT# = m.PRODUCERC#
	WHERE m.TITLE = 'Star Wars'
);

--Problem 2
SELECT DISTINCT
	me.NAME
FROM MOVIEEXEC AS me
JOIN MOVIE AS m	
	ON me.CERT# = m.PRODUCERC#
WHERE m.TITLE IN (
	SELECT
		ss.MOVIETITLE
	FROM STARSIN AS ss
	JOIN MOVIESTAR AS ms
		ON ss.STARNAME = ms.NAME
	WHERE ms.NAME = 'Harrison Ford'
);

--Problem 3
SELECT DISTINCT
	s.NAME,
	ss.STARNAME
FROM STARSIN AS ss
JOIN MOVIE AS m
	ON ss.MOVIETITLE = m.TITLE
JOIN (
	SELECT
		s.NAME
	FROM STUDIO AS s
	JOIN MOVIE AS m
		ON s.NAME = m.STUDIONAME
) AS s
ON m.STUDIONAME = s.NAME
ORDER BY s.NAME ASC

--Problem 4
SELECT 
	ss.STARNAME,
	me.NETWORTH,
	m.TITLE
FROM STARSIN AS ss
JOIN MOVIE AS m
	ON ss.MOVIETITLE = m.TITLE
JOIN MOVIEEXEC AS me 
ON m.PRODUCERC# = me.CERT#
WHERE me.NETWORTH = (
	SELECT TOP(1)
		me.NETWORTH
	FROM MOVIEEXEC AS me
	ORDER BY me.NETWORTH DESC 
);

--Problem 5
SELECT
	ms.NAME,
	ss.MOVIETITLE
FROM MOVIESTAR AS ms
LEFT JOIN STARSIN AS ss
	ON ms.NAME = ss.STARNAME
WHERE ss.MOVIETITLE IS NULL

--Part 2
USE pc


--Part 3
USE ships