--Part 1
USE movies

--Problem 1
SELECT
	m.TITLE,
	me.NAME
FROM MOVIEEXEC AS me
JOIN MOVIE AS m
	ON me.CERT# = m.PRODUCERC#
WHERE me.NAME = (
	SELECT
		me.NAME
	FROM MOVIEEXEC AS me
	JOIN MOVIE	AS m
		ON me.CERT# = m.PRODUCERC#
	WHERE m.TITLE = 'Star Wars'
);

--Problem 2
SELECT DISTINCT
	me.NAME
FROM MOVIEEXEC AS me
JOIN MOVIE AS m	
	ON me.CERT# = m.PRODUCERC#
WHERE m.TITLE IN (
	SELECT
		ss.MOVIETITLE
	FROM STARSIN AS ss
	JOIN MOVIESTAR AS ms
		ON ss.STARNAME = ms.NAME
	WHERE ms.NAME = 'Harrison Ford'
);

--Problem 3
SELECT DISTINCT
	s.NAME,
	ss.STARNAME
FROM STARSIN AS ss
JOIN MOVIE AS m
	ON ss.MOVIETITLE = m.TITLE
JOIN (
	SELECT
		s.NAME
	FROM STUDIO AS s
	JOIN MOVIE AS m
		ON s.NAME = m.STUDIONAME
) AS s
ON m.STUDIONAME = s.NAME
ORDER BY s.NAME ASC

--Problem 4
SELECT 
	ss.STARNAME,
	me.NETWORTH,
	m.TITLE
FROM STARSIN AS ss
JOIN MOVIE AS m
	ON ss.MOVIETITLE = m.TITLE
JOIN MOVIEEXEC AS me 
ON m.PRODUCERC# = me.CERT#
WHERE me.NETWORTH = (
	SELECT TOP(1)
		me.NETWORTH
	FROM MOVIEEXEC AS me
	ORDER BY me.NETWORTH DESC 
);

--Problem 5
SELECT
	ms.NAME,
	ss.MOVIETITLE
FROM MOVIESTAR AS ms
LEFT JOIN STARSIN AS ss
	ON ms.NAME = ss.STARNAME
WHERE ss.MOVIETITLE IS NULL

--Part 2
USE pc

--Problem 1
SELECT
	p.maker,
	p.model,
	p.type
FROM [product] AS p
LEFT JOIN laptop AS l
	ON p.model = l.model
LEFT JOIN pc 
	ON p.model = pc.model
LEFT JOIN printer AS pr 
	ON p.model = pr.model
WHERE l.model IS NULL
	AND pc.model IS NULL
	AND pr.model IS NULL

--Problem 2
(
	SELECT
		p.maker
	FROM product AS p
	JOIN laptop AS l
		ON p.model = l.model
)
INTERSECT
(
	SELECT
		p.maker
	FROM product AS p
	JOIN printer AS pr
		ON p.model = pr.model
)

--Problem 3
SELECT
	l1.hd
FROM laptop AS l1
JOIN laptop AS l2
	ON l1.hd = l2.hd
WHERE l1.code != l2.code

--Problem 3 second way
SELECT DISTINCT
	l1.hd
FROM laptop AS l1
WHERE (
	SELECT 
		COUNT(*)
	FROM laptop AS l2
	WHERE l2.hd = l1.hd
) > 1

--Problem 4
SELECT
	*
FROM pc
LEFT JOIN product AS p
	ON pc.model = p.model
WHERE p.maker IS NULL

--Part 3
USE ships

--Problem 1
SELECT
	*
FROM SHIPS AS s
JOIN CLASSES AS c
	ON s.CLASS = c.CLASS

--Problem 2
SELECT
	*
FROM SHIPS AS s1
RIGHT JOIN CLASSES AS c
	ON s1.CLASS = c.CLASS
WHERE s1.CLASS IS NOT NULL
	OR s1.CLASS IS NULL
	OR c.CLASS IN (
		SELECT DISTINCT
		s2.NAME
		FROM SHIPS AS s2
	);

--Problem 3
SELECT DISTINCT
	c.COUNTRY,
	s.NAME
FROM CLASSES AS c
LEFT JOIN SHIPS AS s
	ON c.CLASS = s.CLASS
WHERE s.NAME NOT IN (
	SELECT	
		o.SHIP
	FROM OUTCOMES AS o
)


--Problem 4
SELECT
	s.NAME AS [Ship Name]
FROM SHIPS AS s
JOIN CLASSES AS c
	ON s.CLASS = c.CLASS
WHERE c.NUMGUNS >= 7
	AND LAUNCHED = 1916

--Problem 5
SELECT
	o.SHIP,
	b.DATE
FROM OUTCOMES AS o
LEFT JOIN BATTLES AS b
	ON o.BATTLE = b.NAME
WHERE o.RESULT = 'sunk'
ORDER BY b.NAME ASC

--Problem 6
SELECT
	s.NAME,
	c.DISPLACEMENT,
	s.LAUNCHED
FROM SHIPS AS s
LEFT JOIN CLASSES AS c
	ON s.CLASS = c.CLASS
WHERE s.NAME = c.CLASS

--Problem 7
SELECT
	*
FROM CLASSES AS c
WHERE c.CLASS NOT IN (
	SELECT DISTINCT
		s.CLASS
	FROM SHIPS AS s
)

--Problem 8
SELECT
	s.NAME,
	c.DISPLACEMENT,
	c.NUMGUNS,
	o.RESULT
FROM CLASSES AS c
RIGHT JOIN SHIPS AS s
	ON c.CLASS = s.CLASS
LEFT JOIN OUTCOMES AS o
	ON s.NAME = o.SHIP
LEFT JOIN BATTLES AS b
	ON o.BATTLE = b.NAME
WHERE b.NAME = 'North Atlantic'